---

- name: establish project facts
  set_fact:
    project:
      "{{ default_project | combine(project, recursive=True) }}"
    build:
      "{{ default_build | combine(build | default({}), recursive=True) }}"
    project_root_path: "{{ path + '/' + (project['name'] | lower | replace(' ', substitutes[' '])) }}"

- name: establish project skeleton
  when: item.use | default(true)
  file:
    path: "{{ project_root_path }}/{{ item.dest }}"
    state: directory
  loop:
    - dest: "build"
    - dest: "include/{{ project_root_path | basename }}"
    - dest: "src"
      use: "{{ not project['attributes']['header_only'] }}"
    - dest: "etc"
    - dest: "docs"
    - dest: "tests"
      use: "{{ tests | length > 0 }}"

- include_tasks: cmake.yml

- name: establish project readme
  template:
    src: "README.md.j2"
    dest: "{{ project_root_path }}/README.md"

- name: establish project license
  import_role:
    name: "{{ role_path }}/../../license"
  vars:
    license: "{{ project['license'] }}"

- name: identify software version control in project directory
  stat:
    path: "{{ project_root_path }}/.git"
  register: git_config

- name: establish ignore file
  when: git_config.stat.isdir is defined and git_config.stat.isdir
  import_role:
    name: "{{ role_path }}/../../ignore_file"
  vars:
    path: "{{ project_root_path }}"
    language: "C++"
    ignore:
      - "build/"
      - "lib/"

- name: establish clang-format
  when: format is defined
  copy:
    content: "{{ format }}"
    dest: "{{ project_root_path }}/.clang-format"
