---
# vi: ft=ansible.yaml

- name: establish updated facts
  set_fact:
    project:
      "{{ project | combine(
         {
           'owner': project['owner'] if project['owner'] is defined else project['author']['name'] if project.get('author',{}).get('name',{}) else '',
           'normalized_name': project['name'] | lower | replace(' ', substitutes[' ']) ,
           'path': path + '/' + (project['name'] | lower | replace(' ', substitutes[' ']))
         }, recursive=True) }}"

- name: establish project skeleton
  when: item.use | default(true)
  file:
    path: "{{ project['path'] }}/{{ item.dest }}"
    state: directory
  loop:
    - dest: "build"
    - dest: "include"
    - dest: "src"
    - dest: "lib"
    - dest: "etc"
    - dest: "docs"
    - dest: "tests"
      use: "{{ tests | length > 0 }}"

- include_tasks: build/cmake.yml

- name: establish project readme
  template:
    src: "README.md.j2"
    dest: "{{ project['path'] }}/README.md"

- name: establish project license
  import_role:
    name: "{{ role_path }}/../../license"
  vars:
    license: "{{ project['license'] | default('wtfpl') }}"

- name: identify software version control in project directory
  stat:
    path: "{{ project['path'] }}/.git"
  register: git_config

- name: establish ignore file
  when: git_config.stat.isdir is defined and git_config.stat.isdir
  import_role:
    name: "{{ role_path }}/../../ignore_file"
  vars:
    path: "{{ project['path'] }}"
    language: "C++"
    ignore:
      - "build/"
      - "lib/"

- name: establish clang-format
  when: format is defined
  copy:
    content: "{{ format }}"
    dest: "{{ project['path'] }}/.clang-format"
