---

- name: prepare facts
  set_fact:
    corrected_name: "{{ project['name'] | replace(' ', '_') | lower }}"

- name: normalize input facts
  set_fact:
    project:
      path: "{{ path }}/{{ corrected_name }}/"
      owner: "{{ project['owner'] if project['owner'] is defined else project['author']['name'] if project.get('author',{}).get('name',{}) else '' }}"

- name: establish project directory skeleton
  file:
    path: "{{ project['path'] }}/{{ item }}"
    state: directory
  loop:
    - ""
    - "{{ corrected_name }}"
    - "bin"
    - "tests"

- name: establish project files
  template:
    src: "{{ item.src }}"
    dest: "{{ project['path'] }}/{{ item.dest }}"
  loop:
    - src: setup.py.j2
      dest: setup.py
    - src: empty.py.j2
      dest: "{{ corrected_name }}/__init__.py"
    - src: README.md.j2
      dest: README.md

- name: add project license
  when: project['license'] is defined
  import_role:
    name: "{{ role_path }}/../../license"
  vars:
    license: "{{ project['license'] }}"

- name: add ignore file
  when: scm is defined
  import_role:
    name: "{{ role_path }}/../../ignore_file"
  vars:
    path: "{{ project['path'] }}"
    language: Python
    ignore: ["bin/"]
